### ISSUE TITLE
`input()` returns an empty string when Vim from vim-appimage is used

### ISSUE THREAD

**Issue by lambdalisue** [thinca/action-setup-vim#11]
### Describe the bug

It seems `input()` returns an empty string when Vim installed by vim-appimage is used. Probably it's not a bug but limitation or issue on vim-appimage side?

```
input (vim) ... input() ... returns user input text => ./denops_std/function/input_test.ts:17:17
error: AssertionError: Values are not equal.


    [Diff] Actual / Expected


-   
+   Hello world!


  throw new AssertionError(message);
        ^
    at assertEquals (https://deno.land/std@0.188.0/testing/asserts.ts:189:9)
    at fn (file:///home/runner/work/deno-denops-std/deno-denops-std/repo/denops_std/function/input_test.ts:33:13)
    at eventLoopTick (ext:core/01_core.js:165:11)
    at async innerWrapped (ext:cli/40_testing.js:479:5)
    at async asyncOpSanitizer (ext:cli/40_testing.js:145:27)
    at async resourceSanitizer (ext:cli/40_testing.js:361:25)
    at async exitSanitizer (ext:cli/40_testing.js:410:27)
    at async Object.outerWrapped [as fn] (ext:cli/40_testing.js:424:14)
    at async TestContext.step (ext:cli/40_testing.js:1082:22)
    at async fn (file:///home/runner/work/deno-denops-std/deno-denops-std/repo/denops_std/function/input_test.ts:17:9)
```

### How to reproduce the problem

It's a bit complicated because I've noticed this issue when running tests of denops_std but what the test does is

1. `au CmdlineEnter * call feedkeys("Hello world\<CR>", "t")`
2. `echomsg input("")`

##### Build
![CleanShot 2023-05-22 at 19 02 10](https://github.com/thinca/action-setup-vim/assets/546312/39485556-12e2-4728-aec0-4bbc7bbf3671)

##### AppImage
![CleanShot 2023-05-22 at 19 01 40](https://github.com/thinca/action-setup-vim/assets/546312/e83063c4-f890-4f97-bef0-37b50684260d)
##### Build

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 22 2023 09:40:58)
Included patches: 1-14[9](https://github.com/vim-denops/deno-denops-std/actions/runs/5044225608/jobs/9046994878#step:8:10)9
Compiled by runner@fv-az397-676
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term -gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           -python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          -ruby              +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            +X[11](https://github.com/vim-denops/deno-denops-std/actions/runs/5044225608/jobs/9046994878#step:8:12)
+digraphs          +mouse             -sound             +xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/home/runner/work/_temp/vim/v9.0.[14](https://github.com/vim-denops/deno-denops-std/actions/runs/5044225608/jobs/9046994878#step:8:15)99/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lselinux
```

##### AppImage

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr 30 2023 01:06:08)
Included patches: 1-1499
Compiled by runner@fv-az1[10](https://github.com/vim-denops/deno-denops-std/actions/runs/5044300803/jobs/9047209201#step:8:11)8-678
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       +tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
+balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
+browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl              +title
+channel           +ipv6              +persistent_undo   +toolbar
+cindent           +job               +popupwin          +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           +python/dyn        +viminfo
+cmdline_info      +libcall           +python3/dyn       +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby              +wildignore
+cursorbind        +lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con_gui    +mksession         +smartindent       +writebackup
+diff              +modify_fname      +sodium            +X[11](https://github.com/vim-denops/deno-denops-std/actions/runs/5044300803/jobs/9047209201#step:8:12)
+digraphs          +mouse             +sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "././/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I././/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng[16](https://github.com/vim-denops/deno-denops-std/actions/runs/5044300803/jobs/9047209201#step:8:17) -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I././/lib/x86_64-linux-gnu/glib-2.0/include -Wno-deprecated-declarations -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -Wl,-E -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lselinux -lcanberra -lsodium -lrt -ldl -L/usr/lib -llua5.3 -Wl,-E -fstack-protector-strong -L/usr/local/lib -L././/lib/x86_64-linux-gnu/perl/5.[30](https://github.com/vim-denops/deno-denops-std/actions/runs/5044300803/jobs/9047209201#step:8:31)/CORE -lperl -ldl -lm -lpthread -lcrypt -L././/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.7 -lm -L/usr/lib
```

**Comment by thinca** [comment]
Could you try AppImage without this action?
If you can reproduce this bug, it is an issue on AppImage.

**Comment by lambdalisue** [comment]
OK but I need to prepare Linux environment first so takes time...

**Comment by lambdalisue** [comment]
I'm sorry that I totally forgot about this issue.

Well, I recently switched to https://github.com/rhysd/action-setup-vim so I don't have enough motivation to prepare AppImage by myself. Sorry for that.
